### ISSUE TITLE
Unclear system requirements in documentation

### ISSUE THREAD

**Issue by tansy** [facebook/openzl#112]
**Describe the bug**
 
Out of curiosity I tried it and immediately got an error, both in GCC and in Clang:

```
g++ -I. -Iinclude -Isrc -Icpp/include -Icpp/src -Ideps/zstd/lib/   -O1 -std=c++1z   -g -Wall -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wundef -Wpointer-arith -Wvla -Wformat=2 -Wfloat-equal -Wswitch-enum -Wno-unused-function   -O3 -MT cachedObjs/0ee53bc7040f0db769d08186a22dfe00/cli/args/ArgsUtils.o -MMD -MP -MF cachedObjs/0ee53bc7040f0db769d08186a22dfe00/cli/args/ArgsUtils.d -c cli/args/ArgsUtils.cpp -o cachedObjs/0ee53bc7040f0db769d08186a22dfe00/cli/args/ArgsUtils.o
In file included from /usr/include/c++/8.2.0/bits/locale_conv.h:41,
                 from /usr/include/c++/8.2.0/locale:43,
                 from /usr/include/c++/8.2.0/bits/fs_path.h:38,
                 from /usr/include/c++/8.2.0/filesystem:37,
                 from cli/args/ArgsUtils.cpp:3:
/usr/include/c++/8.2.0/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = openzl::visualizer::CompressionTraceHooks]’:
/usr/include/c++/8.2.0/bits/unique_ptr.h:274:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = openzl::visualizer::CompressionTraceHooks; _Dp = std::default_delete<openzl::visualizer::CompressionTraceHooks>]’
cpp/include/openzl/cpp/CCtx.hpp:110:72:   required from here
/usr/include/c++/8.2.0/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘openzl::visualizer::CompressionTraceHooks’
  static_assert(sizeof(_Tp)>0,
                ^~~~~~~~~~~
```

**steps to reproduce**

`$ make`

**Expected behavior**

To be able to compile.

**Desktop (please complete the following information):**
 - OS: Linux x86
 - Compiler GCC, Clang
 - Flags: default
 
 - Build system:. Makefile

**Additional context**

What is compiler minimum requirement for this program, as that's what is the issue here, even though it supposed to provide full [C++11 support](https://gcc.gnu.org/projects/cxx-status.html#cxx11) since long time, and if that's about C11/C++11, it should work.

It would make sense to put it in \`INSTALL' ot `Building.md' or something like that. I know there are some instructions in Readme, but they are not very detailed, and don't include troubleshooting of common, or already solved problems.

**Comment by terrelln** [comment]
We currently require C++17 to compile our C++, and C11 to compile our C code.

It definitely makes sense to list it more clearly in our docs. We also aim to drop that requirement down to at least C++14, but there is a bit of work to do to remove some C++17-isms.

In the meantime, that particular change was recently introduced. You may be able to compile in our `v0.1.0` release:

https://github.com/facebook/openzl/releases/tag/v0.1.0

However, you also may just run into another issue down the line.

**Comment by Victor-C-Zhang** [comment]
Thank you for the report @tansy. I've put up a potential fix in #113, let me know if the problem still repros with this. I wasn't able to replicate the build failure on my machine, or indeed on any of our CI jobs. Can you provide some more details on your machine and compiler? Maybe there's something being lost in the nuance here.

**Comment by Victor-C-Zhang** [comment]
> In the meantime, that particular change was recently introduced. You may be able to compile in our `v0.1.0` release:

This has been in the codebase for a couple months, and consistently passing CI. This will certainly also be in `v0.1.0`. I think the particular compiler setup is unearthing some latent UB that may be worth stamping out elsewhere.

**Comment by tansy** [comment]
> We currently require C++17 to compile 

Readme say only about C11.

> You may be able to compile in our v0.1.0 release:

Trips in the same place, the same way.

> potential fix in \#113

Yes, this worked.
But there is [more](https://ufile.io/3q808wy3). Lot more.

**Comment by terrelln** [comment]
> But there is more. Lot more.

Yeah, that makes sense, given that we require C++17. We will update the README to state that.

**Comment by Victor-C-Zhang** [comment]
> Yes, this worked. But there is [more](https://ufile.io/3q808wy3). Lot more.

I'll try to go through the logs and fix what I can see. But I'm going to need more info from you to hunt down a repro. If you could provide
- `gcc --version` and `g++ --version`
- `make --version`
- `cat /etc/os-release`
- `lscpu`
- Whether you're in a windows subsystem

**Comment by Victor-C-Zhang** [comment]
@terrelln here's one of the errors. What do you make of it?
```
/usr/lib/gcc/i686-pc-linux-gnu/8.2.0/include/emmintrin.h:700:1: error: inlining failed in call to always_inline ‘_mm_loadu_si128’: target specific option mismatch
 _mm_loadu_si128 (__m128i_u const *__P)
 ^~~~~~~~~~~~~~~
In file included from src/openzl/codecs/common/row_table.h:9,
                 from src/openzl/codecs/lz/encode_match_finder_greedy_field_lz.c:7:
src/openzl/shared/simd_wrapper.h:83:12: note: called from here
     return _mm_loadu_si128((ZL_Vec128 const*)ptr);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [cachedObjs/0ee53bc7040f0db769d08186a22dfe00/src/openzl/codecs/lz/encode_match_finder_greedy_field_lz.o] Error 1
```

**Comment by tansy** [comment]
GCC-8.2 (as seen in log)
make: 4.4.1
OS: Slackaware 14
Arch: i686, 32-bit, 64-bit (lscpu)

> What do you make of it?

That this SIMD instruction is not present in CPU or maybe rather not recognized by compiler or some switch (-sse -sse2 -ssse3) is not on.
In first case I can't do anything with it, with second, it's makefile's job to turn stuff on.

Full [log](https://dpaste.com/HMBC9Z6C8) for this file says:

```
warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
```
So it's SSE that is not enabled, that's wha I make of it.


I didn't say I'm able to compile it, and/or use it on that machine.
I said, that in Readme it was, and still is, stated about C11, which I happily 'support', and not about C++17. I know, that this compiler does not have full C++17 support. If it was in the Readme, I wouldn't try it, as I know weekday my compiler can and cannot do.
I could run GCC-12 in Windows @wine, but it's slow, so I'll stick to what I already have.

PS. Try [this](https://dpaste.org/peShB), it should give you live Linux rougly equivalent to mine. Have fun.

**Comment by Victor-C-Zhang** [comment]
Thanks for the clarifications. #121 adds system requirements explicitly to both the README.md and the quick-start guide. Closing this issue as resolved. Feel free to re-open if there are more concerns.
